=== joaopgrassi/otel-recipes/otel-recipes-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "https://github.com/joaopgrassi/otel-recipes/otel-recipes-schema.json",
  "title": "JSON Schema for OTel recipe files",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "The unique identifier of the sample app. E.g. console, webapp, rest-api"
    },
    "languageId": {
      "type": "string",
      "description": "The unique identifier of the programming language. MUST be one of the suggested by the schema",
      "enum": ["csharp", "js", "go", "java", "python"]
    },
    "signal": {
      "type": "string",
      "description": "The unique identifier of the telemetry signal. MUST be one of the suggested by the schema",
      "enum": ["traces", "metrics", "logs"]
    },
    "displayName": {
      "type": "string",
      "description": "The user friendly name of the sample app. This is shown on the website (filters)",
      "maxLength": 100
    },
    "description": {
      "type": "string",
      "description": "A brief description of the sample app. This is shown in the 'sample metadata' section on the website",
      "maxLength": 250
    },
    "tags": {
      "type": "array",
      "description": "Related tags with the language/technology of the recipe.",
      "items": {
        "type": "string",
        "enum": ["console", "api", "db", "http", "web", "manual", "automatic"]
      },
      "maxItems": 4,
      "additionalItems": false
    },
    "sourceRoot": {
      "type": "string",
      "description": "The URL to the root directory of the sample app on GitHub. It's best to use a link with a ref to a tag/release version instead of using 'main'",
      "format": "uri"
    },
    "steps": {
      "type": "array",
      "description": "The list steps necessary to configure OpenTelemetry for the sample",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/stepContent"
      }
    },
    "dependencies": {
      "type": "array",
      "description": "The list of dependencies (packages) necessary to configure OpenTelemetry for the sample",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/dependencyContent"
      }
    }
  },

  "required": [
    "id",
    "languageId",
    "signal",
    "displayName",
    "description",
    "sourceRoot",
    "steps",
    "dependencies"
  ],

  "definitions": {
    "stepContent": {
      "type": "object",
      "properties": {
        "displayName": {
          "type": "string",
          "description": "The user friendly name of the step. This is shown on the website in the list of steps to follow. E.g. Configure the exporter, Configure the Trace Provider"
        },
        "description": {
          "type": "string",
          "description": "A brief description of the step"
        },
        "order": {
          "type": "integer",
          "description": "The order in which this step should appear in the list. Starting with 1 for the first step",
          "default": 1
        },
        "source": {
          "type": "string",
          "description": "The raw URL (raw.githubusercontent.com) to the file in the sample app that contains the code for this step. It's best to use a link with a ref to a tag/release version instead of using 'main'",
          "format": "uri"
        },
        "required": {
          "type": "boolean",
          "description": "Indicates if this step is mandatory for the user or not",
          "default": true
        }
      },
      "required": ["displayName", "order", "source"]
    },
    "dependencyContent": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The identifier of the dependency/package the user needs to install"
        },
        "version": {
          "type": "string",
          "description": "The version of the depedency/package required for the sample"
        }
      },
      "required": ["id", "version"]
    }
  }
}

=== joaopgrassi/otel-recipes/src/python/traces/console/recipefile.json
{
  "$schema": "../../../../otel-recipes-schema.json",
  "id": "python.console.traces",
  "languageId": "python",
  "signal": "traces",
  "displayName": "Console App",
  "tags": ["console", "manual"],
  "description": "A python console application instrumented with OpenTelemetry that generates a trace.",
  "sourceRoot": "https://github.com/joaopgrassi/otel-recipes/tree/main/src/python/traces/console",
  "steps": [
    {
      "displayName": "Configure the SDK",
      "order": 1,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/python/traces/console/app.py"
    }
  ],
  "dependencies": [
    {
      "id": "opentelemetry-api",
      "version": "1.24"
    },
    {
      "id": "opentelemetry-sdk",
      "version": "1.24"
    },
    {
      "id": "opentelemetry-exporter-otlp-proto-grpc",
      "version": "1.24"
    }
  ]
}

=== joaopgrassi/otel-recipes/src/python/metrics/console/recipefile.json
{
  "$schema": "../../../../otel-recipes-schema.json",
  "languageId": "python",
  "signal": "metrics",
  "id": "python-console-metrics",
  "displayName": "Console App",
  "tags": [],
  "description": "A python console application instrumented with OpenTelemetry that generate metrics.",
  "sourceRoot": "https://github.com/joaopgrassi/otel-recipes/tree/main/src/python/metrics/console",
  "steps": [
    {
      "displayName": "Configure the SDK",
      "order": 1,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/python/metrics/console/app.py"
    }
  ],
  "dependencies": [
    {
      "id": "opentelemetry-api",
      "version": "1.24"
    },
    {
      "id": "opentelemetry-sdk",
      "version": "1.24"
    },
    {
      "id": "opentelemetry-exporter-otlp-proto-grpc",
      "version": "1.24"
    }
  ]
}

=== joaopgrassi/otel-recipes/src/java/logs/console/recipefile.json
{
  "$schema": "../../../../otel-recipes-schema.json",
  "id": "java-logs-console",
  "languageId": "java",
  "signal": "logs",
  "displayName": "Console App",
  "tags": [],
  "description": "A Java console application instrumented with OpenTelemetry that generate logs.",
  "sourceRoot": "https://github.com/joaopgrassi/otel-recipes/tree/main/src/java/logs/console",
  "steps": [
    {
      "displayName": "Configure the SDK and Log a message",
      "order": 1,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/java/logs/console/app/src/main/java/otel/recipes/App.java"
    }
  ],
  "dependencies": [
    {
      "id": "io.opentelemetry:opentelemetry-bom",
      "version": "1.37.0"
    },
    {
      "id": "io.opentelemetry:opentelemetry-api",
      "version": "1.37.0"
    },
    {
      "id": "io.opentelemetry:opentelemetry-exporter-otlp",
      "version": "1.37.0"
    },
    {
      "id": "io.opentelemetry:opentelemetry-sdk",
      "version": "1.37.0"
    },
    {
      "id": "io.opentelemetry.semconv:opentelemetry-semconv",
      "version": "1.23.1-alpha"
    },
    {
      "id": "org.apache.logging.log4j:log4j-bom:2.23.1",
      "version": "2.23.1"
    },
    {
      "id": "org.apache.logging.log4j:log4j-api",
      "version": "2.23.1"
    },
    {
      "id": "org.apache.logging.log4j:log4j-core",
      "version": "2.23.1"
    },
    {
      "id": "io.opentelemetry.instrumentation:opentelemetry-log4j-appender-2.17",
      "version": "2.2.0-alpha"
    }
  ]
}

=== joaopgrassi/otel-recipes/src/csharp/logs/aspnet-api/recipefile.json
{
  "$schema": "../../../../otel-recipes-schema.json",
  "id": "csharp.aspnetapi.logs",
  "languageId": "csharp",
  "signal": "logs",
  "displayName": "ASP.NET Core API",
  "tags": ["api", "manual"],
  "description": "An ASP.NET Core API instrumented with OpenTelemetry that generates logs when the /helloworld endpoint is called",
  "sourceRoot": "https://github.com/joaopgrassi/otel-recipes/tree/main/src/csharp/logs/aspnet-api",
  "steps": [
    {
      "displayName": "Configure the SDK",
      "order": 1,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/csharp/logs/aspnet-api/Program.cs"
    },
    {
      "displayName": "Record a log message",
      "order": 2,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/csharp/logs/aspnet-api/Controllers/HelloWorldController.cs"
    }
  ],
  "dependencies": [
    {
      "id": "OpenTelemetry.Exporter.OpenTelemetryProtocol",
      "version": "1.8.1"
    },
    {
      "id": "OpenTelemetry.Extensions.Hosting",
      "version": "1.8.1"
    },
    {
      "id": "OpenTelemetry.Instrumentation.AspNetCore",
      "version": "1.8.1"
    },
    {
      "id": "OpenTelemetry.Instrumentation.Http",
      "version": "1.8.1"
    }
  ]
}

=== joaopgrassi/otel-recipes/src/go/traces/console/recipefile.json
{
  "$schema": "../../../../otel-recipes-schema.json",
  "id": "go.console.traces",
  "languageId": "go",
  "signal": "traces",
  "displayName": "Console App",
  "tags": ["console", "manual"],
  "description": "A go console application instrumented with OpenTelemetry that generates a trace.",
  "sourceRoot": "https://github.com/joaopgrassi/otel-recipes/tree/main/src/go/traces/console",
  "steps": [
    {
      "displayName": "Configure the SDK",
      "order": 1,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/go/traces/console/app.go"
    }
  ],
  "dependencies": [
    {
      "id": "go.opentelemetry.io/otel",
      "version": "v1.26.0"
    },
    {
      "id": "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc",
      "version": "v1.26.0"
    },
    {
      "id": "go.opentelemetry.io/otel/sdk",
      "version": "v1.26.0"
    },
    {
      "id": "go.opentelemetry.io/otel/trace",
      "version": "v1.26.0"
    }
  ]
}

=== joaopgrassi/otel-recipes/src/csharp/traces/console/recipefile.json
{
  "$schema": "../../../../otel-recipes-schema.json",
  "id": "csharp.console.traces",
  "languageId": "csharp",
  "signal": "traces",
  "displayName": "Console App",
  "tags": ["console", "manual"],
  "description": "A C# console application instrumented with OpenTelemetry that generates a trace.",
  "sourceRoot": "https://github.com/joaopgrassi/otel-recipes/tree/main/src/csharp/traces/console",
  "steps": [
    {
      "displayName": "Configure the SDK",
      "order": 1,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/csharp/traces/console/App.cs"
    }
  ],
  "dependencies": [
    {
      "id": "OpenTelemetry",
      "version": "1.8.1"
    },
    {
      "id": "OpenTelemetry.Exporter.OpenTelemetryProtocol",
      "version": "1.8.1"
    }
  ]
}

=== joaopgrassi/otel-recipes/src/java/traces/springboot-api/recipefile.json
{
  "$schema": "../../../../otel-recipes-schema.json",
  "id": "java.springbootapi.traces",
  "languageId": "java",
  "signal": "traces",
  "displayName": "Spring Boot API",
  "tags": [],
  "description": "A Spring Boot API instrumented with OpenTelemetry Spring Boot starter that generates a trace when the /helloworld endpoint is called.",
  "sourceRoot": "https://github.com/joaopgrassi/otel-recipes/tree/main/src/java/trace/springboot-api",
  "steps": [
    {
      "displayName": "Add the Spring Boot Starter dependency",
      "order": 1,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/java/trace/springboot-api/build.gradle#L23-L27"
    },
    {
      "displayName": "Create a span",
      "order": 2,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/java/trace/springboot-api/src/main/java/com/otel/recipes/springbootapi/HelloWorldController.java#L26"
    }
  ],
  "dependencies": [
    {
      "id": "io.opentelemetry:opentelemetry-bom",
      "version": "1.36.0"
    },
    {
      "id": "io.opentelemetry:opentelemetry-api",
      "version": "1.36.0"
    },
    {
      "id": "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha",
      "version": "2.2.0-alpha"
    },
    {
      "id": "io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter",
      "version": "2.2.0-alpha"
    }
  ]
}

=== joaopgrassi/otel-recipes/src/csharp/trace/console/recipefile.json
{
  "$schema": "../../../../otel-recipes-schema.json",
  "id": "csharp-console",
  "languageId": "csharp",
  "signal": "traces",
  "displayName": "Console App",
  "tags": [],
  "description": "A C# console application instrumented with OpenTelemetry that generates a trace.",
  "sourceRoot": "https://github.com/joaopgrassi/otel-recipes/tree/main/src/csharp/trace/console",
  "steps": [
    {
      "displayName": "Configure the SDK",
      "order": 1,
      "source": "https://raw.githubusercontent.com/joaopgrassi/otel-recipes/main/src/csharp/trace/console/App.cs"
    }
  ],
  "dependencies": [
    {
      "id": "OpenTelemetry",
      "version": "1.7.0"
    },
    {
      "id": "OpenTelemetry.Exporter.OpenTelemetryProtocol",
      "version": "1.7.0"
    }
  ]
}
